# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\alexs\Downloads\jet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\alexs\Downloads\jet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	echo >nul && "C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\alexs\Downloads\jet\CMakeFiles C:\Users\alexs\Downloads\jet\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\alexs\Downloads\jet\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jet

# Build rule for target.
jet: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) jet
.PHONY : jet

# fast build rule for target.
jet\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\build
.PHONY : jet\fast

#=============================================================================
# Target rules for targets named jet_app

# Build rule for target.
jet_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) jet_app
.PHONY : jet_app

# fast build rule for target.
jet_app\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet_app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet_app.dir\build
.PHONY : jet_app\fast

app\main.obj: app\main.cpp.obj
.PHONY : app\main.obj

# target to build an object file
app\main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet_app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet_app.dir\app\main.cpp.obj
.PHONY : app\main.cpp.obj

app\main.i: app\main.cpp.i
.PHONY : app\main.i

# target to preprocess a source file
app\main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet_app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet_app.dir\app\main.cpp.i
.PHONY : app\main.cpp.i

app\main.s: app\main.cpp.s
.PHONY : app\main.s

# target to generate assembly for a file
app\main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet_app.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet_app.dir\app\main.cpp.s
.PHONY : app\main.cpp.s

src\helper.obj: src\helper.cpp.obj
.PHONY : src\helper.obj

# target to build an object file
src\helper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\helper.cpp.obj
.PHONY : src\helper.cpp.obj

src\helper.i: src\helper.cpp.i
.PHONY : src\helper.i

# target to preprocess a source file
src\helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\helper.cpp.i
.PHONY : src\helper.cpp.i

src\helper.s: src\helper.cpp.s
.PHONY : src\helper.s

# target to generate assembly for a file
src\helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\helper.cpp.s
.PHONY : src\helper.cpp.s

src\request.obj: src\request.cpp.obj
.PHONY : src\request.obj

# target to build an object file
src\request.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\request.cpp.obj
.PHONY : src\request.cpp.obj

src\request.i: src\request.cpp.i
.PHONY : src\request.i

# target to preprocess a source file
src\request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\request.cpp.i
.PHONY : src\request.cpp.i

src\request.s: src\request.cpp.s
.PHONY : src\request.s

# target to generate assembly for a file
src\request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\request.cpp.s
.PHONY : src\request.cpp.s

src\response.obj: src\response.cpp.obj
.PHONY : src\response.obj

# target to build an object file
src\response.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\response.cpp.obj
.PHONY : src\response.cpp.obj

src\response.i: src\response.cpp.i
.PHONY : src\response.i

# target to preprocess a source file
src\response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\response.cpp.i
.PHONY : src\response.cpp.i

src\response.s: src\response.cpp.s
.PHONY : src\response.s

# target to generate assembly for a file
src\response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\response.cpp.s
.PHONY : src\response.cpp.s

src\router.obj: src\router.cpp.obj
.PHONY : src\router.obj

# target to build an object file
src\router.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\router.cpp.obj
.PHONY : src\router.cpp.obj

src\router.i: src\router.cpp.i
.PHONY : src\router.i

# target to preprocess a source file
src\router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\router.cpp.i
.PHONY : src\router.cpp.i

src\router.s: src\router.cpp.s
.PHONY : src\router.s

# target to generate assembly for a file
src\router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\router.cpp.s
.PHONY : src\router.cpp.s

src\server.obj: src\server.cpp.obj
.PHONY : src\server.obj

# target to build an object file
src\server.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\server.cpp.obj
.PHONY : src\server.cpp.obj

src\server.i: src\server.cpp.i
.PHONY : src\server.i

# target to preprocess a source file
src\server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\server.cpp.i
.PHONY : src\server.cpp.i

src\server.s: src\server.cpp.s
.PHONY : src\server.s

# target to generate assembly for a file
src\server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\jet.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\jet.dir\src\server.cpp.s
.PHONY : src\server.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... jet
	@echo ... jet_app
	@echo ... app/main.obj
	@echo ... app/main.i
	@echo ... app/main.s
	@echo ... src/helper.obj
	@echo ... src/helper.i
	@echo ... src/helper.s
	@echo ... src/request.obj
	@echo ... src/request.i
	@echo ... src/request.s
	@echo ... src/response.obj
	@echo ... src/response.i
	@echo ... src/response.s
	@echo ... src/router.obj
	@echo ... src/router.i
	@echo ... src/router.s
	@echo ... src/server.obj
	@echo ... src/server.i
	@echo ... src/server.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

